services:
  db:
    image: postgres:latest
    container_name: ec_db
    environment:
      POSTGRES_USER: ec_user
      POSTGRES_PASSWORD: ec_password
      POSTGRES_DB: ec_database
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  db_data:
